# Generated by Django 2.0.6 on 2020-09-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialdetail',
            name='R2_Invoice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
